apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 80
  selector:
    app: web
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: dreamwidth/web:latest
        imagePullPolicy: Never
        name: web
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: config
          mountPath: "/dw/etc"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: dw-config

